### PR TITLE
update oc-client-browser package

### PR DESCRIPTION
**Pull request by ricardo-devis-agullo**

### CODE REVIEW

**Review by matteofigus — CHANGES_REQUESTED** [review]
You shouldn't change the OC version here, there is a script to publish OC that will automatically bump the version and generate the changelog.

**Comment by ricardo-devis-agullo** [comment]
> 
> 
> You shouldn't change the OC version here, there is a script to publish OC that will automatically bump the version and generate the changelog.

Good to know! Reverted

**Comment by matteofigus** [comment]
Ok so this seems like it's failing because the oc-client-browser wasn't published. Do you want me to? I think @pbazydlo should have the permissions to do it

**Comment by ricardo-devis-agullo** [comment]
Yes, please! That would be perfect :)

**Comment by pbazydlo** [comment]
I've just published 1.4.0 I'll try to rerun travis

**Review by pbazydlo — APPROVED** [review]

**Comment by pbazydlo** [comment]
@matteofigus when you have time can you approve + publish?

**Review by matteofigus — APPROVED** [review]

**Comment by matteofigus** [comment]
Done, published. Thanks for your help folks!

**Pull request merged**
