### PR TITLE
Respect cdn.maxConcurrentRequests in components-list

### LINKED ISSUE #1179: component-list doesn't respect maxConcurrentRequests
component-list doesn't respect `maxConcurrentRequests` defined in storage adapter.

## *Who* is the bug affecting?
component creators, registry mainteniers

## *What* is affected by this bug?
oc registry

## *When* does this occur?
when publishing a component to registry. More specifically - when refreshing component cache.

## *Where* on the platform does it happen?
oc registry

## *How* do we replicate the issue?
1. Set up oc registry using [oc-azure-storage-adapter](https://www.npmjs.com/package/oc-azure-storage-adapter)
2. Publish a lot of components (more than 20, it was 60 in my case)
3. When publishing a new component, there are chances that it will fail with ECONNRESET error. That's because the adapter defines `maxConcurrentRequests: 20`, but when oc refreshes component list, it doesn't take `maxConcurrentRequests` into account.

## Expected behavior (i.e. solution)
Number of concurrent connections on cache refresh is limited to `maxConcurrentRequests`.

## What version of OC, Node.js and OS are you using?
oc: 0.48.0, node: v14.8.0, os: Windows, Linux

### PR DESCRIPTION
**Pull request by qbikez**
Storage adapter defines `maxConcurrentRequests`, which was used in `components-details`, but not in `components-list`. This causes ECONNRESET errors in azure storage adapter, because too many concurrent connections are made.
Fix by using async.mapLimit.

**Closing issues**

closes #1179

### CODE REVIEW

**Comment by kmcrawford** [comment]
What happens when the other non-experimental storage-adapters don't define maxConcurrentRequests?

**Comment by pbazydlo** [comment]
it's already used in `component-details`, so this property should be defined in all storage adapters, or it would be broken already I think? https://github.com/opencomponents/oc/blob/a4da36da9da78e9307c3fdb85302422e3a8959f1/src/registry/domain/components-details.js#L36

**Comment by pbazydlo** [comment]
it seems other adapters also define this property: https://github.com/opencomponents/storage-adapters/search?q=maxConcurrentRequests

**Comment by pbazydlo** [comment]
@qbikez there seem to be some failing tests, can you check those?

**Comment by kmcrawford** [comment]
It's been a while since I've looked at the code. I would have expected that to be a config in to storage object. My mistake.

**Review by matteofigus — APPROVED** [review]

**Comment by matteofigus** [comment]
LGTM - feel free to merge

**Comment by pbazydlo** [comment]
cheers :) can you publish new version @matteofigus? I can't remember if there are any steps apart from `npm install;npm publish` :P

**Comment by matteofigus** [comment]
ok np published as `v0.48.16`

**Pull request merged**
